### ISSUE TITLE
Balanzierung der Output-Klassen

### ISSUE THREAD

**Issue by laraknapwost** [Co-Re/RescueSnoopy007#30]
siehe Vorlesungsskript ML werden idealerweise balanzierte Output-Klassen verwendet, d.h. jede Klasse sollte gleich oft vorkommen, da sonst eine größere Chance besteht, eine Klasse mit mehr Instanzen vorherzusagen als diejenigen mit weniger Instanzen
Möglichkeit: den Klassen können unterschiedliche Gewichte gegeben werden , Behandlung mittels Ensemble Methoden

**Comment by isabelleveitl** [comment]
#34 wenn ihr OK seid mit "Adoption" als outcome type, dann ist das auch erledigt
